version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily

- package-ecosystem: terraform
  directories:
  - /modules/elastic-ip
  - /modules/ipam
  - /modules/ipam-resource-discovery
  - /modules/managed-prefix-list
  - /modules/prefix-list
  schedule:
    interval: weekly
