# Modules
- color: "fbca04"
  description: "This issue or pull request is related to elastic-ip module."
  name: ":floppy_disk: elastic-ip"
- color: "fbca04"
  description: "This issue or pull request is related to ipam module."
  name: ":floppy_disk: ipam"
- color: "fbca04"
  description: "This issue or pull request is related to ipam-resource-discovery module."
  name: ":floppy_disk: ipam-resource-discovery"
- color: "fbca04"
  description: "This issue or pull request is related to managed-prefix-list module."
  name: ":floppy_disk: managed-prefix-list"
- color: "fbca04"
  description: "This issue or pull request is related to prefix-list module."
  name: ":floppy_disk: prefix-list"
